# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://jhartquist.github.io/notion_orm/"

git_url = "https://github.com/jhartquist/notion_orm/tree/master/"

def custom_doc_links(name): return None
